### ISSUE TITLE
Checking if could make the website into a Progressive Web App

### ISSUE THREAD

**Issue by nybcouncil** [wdmnybcouncil/national-youth-bike-council#10]
Idea by Shraddha:
- Check if we could gracefully convert the React based website of NYBC to a Progressive Web App (PWA). 
- A progressive web app (PWA) is a website that looks and behaves as if it is a mobile app. PWAs are built to take advantage of native mobile device features, without requiring the end user to visit an app store, make a purchase and download software locally. It's basically making a website to be used from mobile as an app without actually developing a native app.
- [A Progressive Web App: What Is It and 10 Reasons Why You Need It](https://www.sam-solutions.com/blog/the-benefits-of-progressive-web-apps-pwa-for-business/)

**Comment by 5hraddha** [comment]
I have converted our web app to a PWA. In order to use our website as a mobile app. You could do:
1. **For Android Users**
- Open the website in Google Chrome or any web browser on your mobile.
- From the top right side, click on the three dots.
- Select **Install App**.
- The app will be installed on your mobile.

2. **For iOS Users**
- Chrome for iOS does not support PWAs. PWAs can be installed using Safari (since iOS 11.3) on iOS and iPadOS.
-  First, navigate to the site in Safari. 
-  Press the "Share" button and select "Add to Home Screen" from the popup. 
- Lastly, tap "Add" in the top right corner to finish installing the PWA.
- You PWA will be installed as a mobile app on your device and you can use it without opening Safari or any other browser.

3. **MacOS**
- On Google Chrome, you will get an "Install App" icon in the URL bar towards the right end.
- Click that to install the app on your MacBook.

**To Dos**:

- [ ] The PWA right not cannot work offline. I need to enable caching.
- [ ] The PWA's splash screen has to be recreated.
